version: '3.1'

services:
  wordpress:
    image: wordpress  
    restart: always
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ../wordpress/:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root